version: '3.3'

services:
  db:
    image: sqltanja
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_User: wordpressuser
      DB_PASSWORD: wordpresspw
      DB_NAME: wordpress
    volumes: 
      - type: volume
        source: dbdata
        target: /var/lib/mysql
   

  wordpress:
    depends_on:
      - db
    image: wordpresstanja
    ports:
      - "80:80"
    volumes: 
     - type: volume
       source: wpuploads 
       target: /var/html/wp-content/uploads/
     - type: volume
       source: wpconfig 
       target: /etc/wordpress/
    restart: always
    environment:
      DB_HOST: db:8080
      DB_User: wordpressuser
      DB_PASSWORD: wordpresspw
      DB_NAME: wordpress

volumes: 
  dbdata:
  wpconfig:
  wpuploads: