version: '3'


services:
  db:
    image: specified123
    ports:
      - "8081:8080"
    restart: always

  wordpress:
    depends_on:
      - db
    image: specified123
    ports:
      - "8081:8080"
    restart: always