version: '3.3'


services:
  db:
    image: tanninchen/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      DB_User: wordpressuser
      DB_PASSWORD: wordpresspw
      DB_NAME: wordpress
    volumes: 
      - type: volume
        source: dbdata
        target: /var/lib/mysql
   

  wordpress:
    depends_on:
      - db
    image: tanninchen/wordpress
    ports:
      - "8000:80"
    volumes: 
     - type: volume
       source: wpuploads 
       target: /var/html/wp-content/uploads/
     - type: volume
       source: wpconfig 
       target: /etc/wordpress/
    restart: always
    environment:
      DB_HOST: db:3306
      DB_User: wordpressuser
      DB_PASSWORD: wordpresspw
      DB_NAME: wordpress

volumes: 
  dbdata:
  wpconfig:
  wpuploads: