version: '3'


services:
  db:
    image: specified123
    ports:
      - "8081:8080"
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYQL_PW: password123

  wordpress:
    depends_on:
      - db
    image: specified123
    ports:
      - "8081:8080"
    restart: always

#volumes: 
